### ISSUE TITLE
Tiny Typo in https://github.com/m5stack/M5Unit-MiniEncoderC/blob/main/examples/getValue/getValue.ino

### ISSUE THREAD

**Issue by MDAR** [m5stack/M5Unit-MiniEncoderC#1]
### Describe the bug

Re :- https://github.com/m5stack/M5Unit-MiniEncoderC/blob/main/examples/getValue/getValue.ino

there is a tiny Typo on line 27

currently 
```
   if (!btn_stauts) {
        sensor.setLEDColor(0, 0x001100);
    }
```

I assume this should be

```
   if (!btn_status) {
        sensor.setLEDColor(0, 0x001100);
    }
```

Likewise

Should the I2C address be set to 

`0x42` on line 11?

(Currently, `uint8_t i2c_address = 0` )

### To reproduce

Simply reviewing the code before trying it

### Expected behavior

get status

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by MDAR** [comment]
When compiing the code in Arduino IDE2.1.1

I get this error

```
 #include "Unit_MiniEncoderC.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: Unit_MiniEncoderC.h: No such file or directory
```


Board manager shows M5Stack (official) version 2.0.07
Library manager shows M5Stack 0.4.4

**Comment by TinyuZhao** [comment]
> When compiing the code in Arduino IDE2.1.1
> 
> I get this error
> 
> ```
>  #include "Unit_MiniEncoderC.h"
>           ^~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> 
> exit status 1
> 
> Compilation error: Unit_MiniEncoderC.h: No such file or directory
> ```
> 
> Board manager shows M5Stack (official) version 2.0.07 Library manager shows M5Stack 0.4.4

You can try this [guide](https://docs.m5stack.com/en/quick_start/library),`Manual Installation of Dependency Libraries`

**Comment by TinyuZhao** [comment]
> ### Describe the bug
> Re :- https://github.com/m5stack/M5Unit-MiniEncoderC/blob/main/examples/getValue/getValue.ino
> 
> there is a tiny Typo on line 27
> 
> currently
> 
> ```
>    if (!btn_stauts) {
>         sensor.setLEDColor(0, 0x001100);
>     }
> ```
> 
> I assume this should be
> 
> ```
>    if (!btn_status) {
>         sensor.setLEDColor(0, 0x001100);
>     }
> ```
> 
> Likewise
> 
> Should the I2C address be set to
> 
> `0x42` on line 11?
> 
> (Currently, `uint8_t i2c_address = 0` )
> 
> ### To reproduce
> Simply reviewing the code before trying it
> 
> ### Expected behavior
> get status
> 
> ### Screenshots
> _No response_
> 
> ### Environment
> * OS:
> * IDE &IDE Version:
> * Repository Version:
> 
> ### Additional context
> _No response_
> 
> ### Issue checklist
> * [x]  I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
> * [x]  My report contains all necessary details

The typo has been fixed.https://github.com/m5stack/M5Unit-MiniEncoderC/commit/7df08c4480cc4a1c8a626c830726e9b86909a5fc
The I2C address does not need to be set.https://github.com/m5stack/M5Unit-MiniEncoderC/blob/ef1eda9f19932e630f5f50d01e1d4e26399c284c/examples/getValue/getValue.ino#L60
